# Docker
# spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/stock_system}
# spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
# spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:2406}
# spring.datasource.driver-class-name=org.postgresql.Driver

# spring.datasource.hikari.connection-timeout=20000
# spring.datasource.hikari.maximum-pool-size=5

# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#local
# spring.datasource.url=jdbc:postgresql://localhost:5432/stock_system
# spring.datasource.username=postgres
# spring.datasource.password=2406
# spring.datasource.driver-class-name=org.postgresql.Driver

# spring.datasource.hikari.connection-timeout=20000
# spring.datasource.hikari.maximum-pool-size=5

# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect



#render deployment
spring.datasource.url=jdbc:postgresql://dpg-d6q4m9k50q8c738fshig-a.singapore-postgres.render.com:5432/stock_system_hr9j?sslmode=require
spring.datasource.username=stock_system_hr9j_user
spring.datasource.password=efQp1IArnrxkQVi9y56cqpHk9XeUDd9d
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true